### ISSUE TITLE
ConnectorPKG.cs - through an error when try to Initialize the connection

### ISSUE THREAD

**Issue by abuldhaka** [Vidyo/VidyoConnector-xamarin#3]
ConnectorPKG.cs file  through an error during Initialization the connection. It happen after app deployment in android media or in Android Emulator.

![capture](https://user-images.githubusercontent.com/28070277/33532640-e207d5d2-d860-11e7-9cf8-b3c40f6a83b5.PNG)

**Comment by NageshDegil** [comment]
[ERROR] FATAL UNHANDLED EXCEPTION: Java.Lang.ClassNotFoundException: com.vidyo.VidyoClient.Connector.ConnectorPkg ---> Java.Lang.ClassNotFoundException: Didn't find class "com.vidyo.VidyoClient.Connector.ConnectorPkg" on path: DexPathList[[zip file "/data/app/com.vidyo.VidyoConnector-1/base.apk"],nativeLibraryDirectories=[/data/app/com.vidyo.VidyoConnector-1/lib/arm, /system/fake-libs, /data/app/com.vidyo.VidyoConnector-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
12-20 14:59:55.468 E/mono-rt (29862):    --- End of inner exception stack trace ---
12-20 14:59:55.468 E/mono-rt (29862):   --- End of managed Java.Lang.ClassNotFoundException stack trace ---
12-20 14:59:55.468 E/mono-rt (29862): java.lang.ClassNotFoundException: com.vidyo.VidyoClient.Connector.ConnectorPkg
12-20 14:59:55.468 E/mono-rt (29862): 	at java.lang.Class.classForName(Native Method)
12-20 14:59:55.468 E/mono-rt (29862): 	at java.lang.Class.forName(Class.java:400)
12-20 14:59:55.468 E/mono-rt (29862): 	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.FormsAppCompatActivity.n_onStart(Native Method)
12-20 14:59:55.468 E/mono-rt (29862): 	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.FormsAppCompatActivity.onStart(FormsAppCompatActivity.java:120)
12-20 14:59:55.468 E/mono-rt (29862): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1256)
12-20 14:59:55.468 E/mono-rt (29862): 	at android.app.Activity.performStart(Activity.java:6973)
12-20 14:59:55.468 E/mono-rt (29862): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2937)
12-20 14:59:55.468 E/mono-rt (29862): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
12-20 14:59:55.468 E/mono-rt (29862): 	at android.app.ActivityThread.-wrap14(ActivityThread.java)
12-20 14:59:55.468 E/mono-rt (29862): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
12-20 14:59:55.468 E/mono-rt (29862): 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-20 14:59:55.468 E/mono-rt (29862): 	at android.os.Looper.loop(Looper.java:154)
12-20 14:59:55.468 E/mono-rt (29862): 	at android.app.ActivityThread.main(ActivityThread.java:6776)
12-20 14:59:55.468 E/mono-rt (29862): 	at java.lang.reflect.Method.invoke(Native Method)
12-20 14:59:55.468 E/mono-rt (29862): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
12-20 14:59:55.468 E/mono-rt (29862): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
12-20 14:59:55.468 E/mono-rt (29862): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.vidyo.VidyoClient.Connector.ConnectorPkg" on path: DexPathList[[zip file "/data/app/com.vidyo.VidyoConnector-1/base.apk"],nativeLibraryDirectories=[/data/app/com.vidyo.VidyoConnector-1/lib/arm, /system/fake-libs, /data/app/com.vidyo.VidyoConnector-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
12-20 14:59:55.468 E/mono-rt (29862): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
12-20 14:59:55.468 E/mono-rt (29862): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
12-20 14:59:55.468 E/mono-rt (29862): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)

**Comment by pfuternik** [comment]
Hi, this ClassNotFoundExcecption is likely due to the fact that your project is not building with the vidyoclient.jar file. Make sure that file is in your project and do the following:
In the Solution pad, right-click on "vidyoclient.jar" and choose "Properties".
In that "Properties" pad, go to the "Build action" field and populate it with "AndroidJavaLibrary".

Let me know if that helps or if you've already figured out the issue.

Thanks,
Phil
